name: generate-srcinfo

concurrency: ci-${{ github.ref }}

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-srcinfo:
    runs-on: windows-latest
    if: ${{ github.repository == 'InitialForce/MINGW-packages' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: binutils
          update: true


      - name: Parse PKGBUILDs and update srcinfo.json
        run: |
          $MSYS2_ROOT=(msys2 -c 'cygpath -w /')
          python -u .ci/ci-generate-srcinfo.py --time-limit 19800 mingw "$MSYS2_ROOT" . srcinfo.json

      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: srcinfo.json

  upload-srcinfo:
    needs: update-srcinfo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: result

      - name: Upload srcinfo.json
        run: |
          gh release upload srcinfo-cache srcinfo.json --clobber --repo "$GITHUB_REPOSITORY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          curl -X POST 'https://packages.msys2.org/api/trigger_update'
